### ISSUE TITLE
integrating machine learning potential model into Lammps

### ISSUE THREAD

**Issue by XinjianOUYANG** [Roy-Kid/extending-lammps-zh#5]
你好，我最近在研究怎么实现lammps和机器学习势函数的c++接口，看了很多资料，也没有清楚的头绪。请问您有什么经验,指导或参考教程吗？

**Comment by Roy-Kid** [comment]
你好，如果你需要写lammps的势函数接口，那这本书里的内容就够用了。其他的设计可以参考deepmd-kit等软件的设计。

**Comment by XinjianOUYANG** [comment]
好的，谢谢！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
